### ISSUE TITLE
I Can't calculate the eao

### ISSUE THREAD

**Issue by DOCNULL** [StrangerZhang/pysot-toolkit#13]

**Comment by DOCNULL** [comment]
since I don't know what the needed format for the out put bbox, and I use the format from the GT_bbox TXT but still get nothing.

**Comment by DOCNULL** [comment]
(tensorflow) G:\Tracking\pysot-toolkit-master>python bin/eval.py --dataset_dir G:\Tracking\pysot-toolkit-master\VOT2016 --dataset VOT2016 --tracker_result_dir G:\Tracking\pysot-toolkit-master\some.txt  --trackers MAX
loading VOT2016: 100%|██████████████████████████████████████| 1/1 [00:00<00:00, 30.35it/s, graduate]
eval ar: 100%|████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.07s/it]
eval eao:   0%|                                                               | 0/1 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\conda\conda\envs\tensorflow\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File ".\pysot\evaluation\eao_benchmark.py", line 43, in eval
    eao = self._calculate_eao(tracker_name, self.tags)
  File ".\pysot\evaluation\eao_benchmark.py", line 111, in _calculate_eao
    max_len = max([len(x) for x in all_overlaps])
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/eval.py", line 147, in <module>
    trackers), desc='eval eao', total=len(trackers), ncols=100):
  File "C:\Users\1\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tqdm\_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "C:\Users\1\AppData\Local\conda\conda\envs\tensorflow\lib\multiprocessing\pool.py", line 731, in next
    raise value
ValueError: max() arg is an empty sequence

**Comment by Puzzle0612** [comment]
Did you find any solutions? I met the same problem as well...

**Comment by Dtappledoghuati** [comment]
> Did you find any solutions? I met the same problem as well...

I also encountered the same problem.

**Comment by harindermashiana** [comment]
Same problem. Please resolve this issue soon, if anybody has found the solution do explain.

**Comment by Dtappledoghuati** [comment]
Set the “results” folder in the folder, the “OTB100” folder in the “results” folder, and the result folders that are run out of various trackers in the “OTB100” folder, such as SiamMask, SiamRPN, etc. , put the results into it.

**Comment by harindermashiana** [comment]
> Set the “results” folder in the folder, the “OTB100” folder in the “results” folder, and the result folders that are run out of various trackers in the “OTB100” folder, such as SiamMask, SiamRPN, etc. , put the results into it.

The problem is with the VOT dataset not OTB and can you be more clear about directories you mentioned?

**Comment by harindermashiana** [comment]
I think there is problem with my results directory, which looks like as follows:
This results directory is placed inside the model directory
```
results
 |VOT2018
   | model
     | result1.txt
     | result2.txt
     ...
```

**Comment by harindermashiana** [comment]
> I think there is problem with my results directory, which looks like as follows:
> This results directory is placed inside the model directory
> 
> ```
> results
>  |VOT2018
>    | model
>      | result1.txt
>      | result2.txt
>      ...
> ```

Solved it. There is supposed to be a directory named baseline in model directory. The .txt files should be in baseline directory.

**Comment by Singapore-mor** [comment]
> Set the “results” folder in the folder, the “OTB100” folder in the “results” folder, and the result folders that are run out of various trackers in the “OTB100” folder, such as SiamMask, SiamRPN, etc. , put the results into it.

Can you draw the success_precision picture?

**Comment by Dtappledoghuati** [comment]
yes

At 2019-11-06 17:23:30, "Singapore-mor" <notifications@github.com> wrote:


Set the “results” folder in the folder, the “OTB100” folder in the “results” folder, and the result folders that are run out of various trackers in the “OTB100” folder, such as SiamMask, SiamRPN, etc. , put the results into it.

Can you draw the success_precision picture?

**Comment by MaMingyueIT** [comment]
Is there a detailed solution？

**Comment by MaMingyueIT** [comment]
download the Raw results in http://www.votchallenge.net/vot2018/results.html
Set --tracker_result_dir to the decompressed address of the above package
Then worked！！

**Comment by zhangyuran-gg** [comment]
设置目录了，仍然没有解决

**Comment by zhangyuran-gg** [comment]
> 

设置目录后就解决了吗

**Comment by bobo-liang** [comment]
请问该问题有解决吗
