### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yongwuML** [StrangerZhang/pysot-toolkit#15]
sorry to bother,
i got a error when run the code.
''Traceback (most recent call last):
  File "eval.py", line 40, in <module>
    trackers), desc='eval success', total=len(trackers), ncols=100):
  File "/home/yongwu/anaconda3/envs/mx/lib/python3.7/site-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/home/yongwu/anaconda3/envs/mx/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
ValueError: could not convert string to float: '198\t214\t34\t81'
"

**Comment by SmallCookier** [comment]
I have the same problem.Do you solve it ?

**Comment by yongwuML** [comment]
the format of the groundtruth or test results is different from pysot-toolkit, you should to change format. googluck！ @SmallCookier

**Comment by Cassiel829** [comment]
@yongwuSHU I met the same problem. Could you show me your tracking results' .txt format? I don't konw how to change the format, Thx

**Comment by momo-github-1984** [comment]
> @yongwuSHU我遇到了同样的问题。您能告诉我您的跟踪结果的.txt格式吗？我不知道如何更改格式，Thx
478.,143.,80.,111.
476.,141.5,80.,111.
大概这样就好了。逗号分隔，数字是浮点数，换行

**Comment by LearnByDoingXW** [comment]
@momo-github-1984 请问你有转换后的结果吗，我按照你的方式进行了转换，虽然不报错，但是不能用，你可以提供一下你的转换结果吗？非常感谢！
