### ISSUE TITLE
question about run eval.py

### ISSUE THREAD

**Issue by Singapore-mor** [StrangerZhang/pysot-toolkit#16]
首先感谢这么棒的工作！
我运行eval.py跑otb100，结果跑出来了，但是success_precision的图没有画出来，报错FileNotFoundError: [WinError 2] 系统找不到指定的文件。pycharm有提示Package requirements 'glob','opencv-python' are not satisfied，不知道是不是这个问题，我应该怎么解决呢？

**Comment by LGBluesky** [comment]
@StrangerZhang 同问，我运行eval.py 跑otb100, 运行环境是 Ubuntu 16.04，, tracekers选用 SiamRPN++ C-COT DaSiamRPN ECO
结果没有跑出来，跑到 eval sucess  就出错了， 提示:
eval success:   0%|                                                           | 0/4 [00:00<?, ?it/s]../tracker_result/SiamRPN++/篮球all.txt
eval success:   0%|                                                           | 0/4 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/xc/anaconda3/envs/siamban/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/media/xc/data/visual obeject tracing/pysot-toolkit-master/pysot/evaluation/ope_benchmark.py", line 50, in eval_success
    success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
  File "/home/xc/anaconda3/envs/siamban/lib/python3.7/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/xc/anaconda3/envs/siamban/lib/python3.7/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/home/xc/anaconda3/envs/siamban/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type array(pyobject, 0d, C)
During: typing of argument at /media/xc/data/visual obeject tracing/pysot-toolkit-master/pysot/utils/statistics.py (104)

File "pysot/utils/statistics.py", line 104:
def success_overlap(gt_bb, result_bb, n_frame):
    thresholds_overlap = np.arange(0, 1.05, 0.05)
    ^

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/eval.py", line 51, in <module>
    trackers), desc='eval success', total=len(trackers), ncols=100):
  File "/home/xc/anaconda3/envs/siamban/lib/python3.7/site-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/home/xc/anaconda3/envs/siamban/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type array(pyobject, 0d, C)
During: typing of argument at /media/xc/data/visual obeject tracing/pysot-toolkit-master/pysot/utils/statistics.py (104)

File "pysot/utils/statistics.py", line 104:
def success_overlap(gt_bb, result_bb, n_frame):
    thresholds_overlap = np.arange(0, 1.05, 0.05)

**Comment by han3889847** [comment]
@LGBluesky  Have you solved this problem？thanks

**Comment by momo-github-1984** [comment]
好吧，我也有这样的问题，大家知道怎么解决吗？

**Comment by gaojian66** [comment]
同样的问题，求解决方案

**Comment by 16534165** [comment]
@LGBluesky 大哥，Have you solved this problem？thanks

**Comment by 16534165** [comment]
> 好吧，我也有这样的问题，大家知道怎么解决吗？
大哥
你解决了吗

**Comment by bibixiuxiuxiu** [comment]
请问这个问题有人解决了吗

**Comment by kaiqidou** [comment]
results文件夹得问题 results--》OTB--》SiamFC--》xxx.txt

**Comment by a81940595** [comment]
要得到指标的本质是  跟踪器（siamfc，siamrpn等测试的输出）在数据集上预测的结果（pred）， 和真实的标签（OTB自带的标注框）对比，得到结果。  所以，你除了OTB自带的标签以外，还需要跟踪器在数据集上跑出来的txt才能正确运行代码， 你这个错误提示可能是因为txt缺失或者对不上

**Comment by JN-Yang** [comment]
我是用的自己做的数据集，这个问题有没有可能是数据集中目标消失，然后gt_rect=[0,0,0,0]导致的
